
name: Vul Test

on:
  push:
    branches:
      - jinghao1-path-1
  pull_request:
    branches:
      - jinghao1-path-1

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Run Vul Container
        env:
          PROJECT_VERSION: 'v1.0.${{ github.run_id }}'
        run: |
          cd /vulnpy
          docker-compose up -d

      - name: Run Vul test
        run: |
          bash /vulnpy/tests/vul-test.sh

